services:
  nginx:
    container_name: onway-nginx
    image: nginx:stable-alpine3.21
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/var/www/html:/var/www/html:ro"
    depends_on:
      - api
    network_mode: "host"
    restart: unless-stopped
  api:
    container_name: onway-api
    image: ${DOCKER_USERNAME}/onway-api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
  migrations:
    container_name: onway-migrations
    image: ${DOCKER_USERNAME}/onway-api:latest
    env_file:
      - .env
    volumes:
      - "./drizzle:/api/drizzle"
    command:
      - "sh"
      - "-c"
      - "npx drizzle-kit migrate"
  debug:
    container_name: onway-debug
    image: ${DOCKER_USERNAME}/onway-api:latest
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "sleep"
      - "infinity"
  database:
    container_name: ${POSTGRES_HOST}
    image: postgres:15.13-alpine3.21
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgresdata:
