services:
  api:
    container_name: onway-api
    image: ${DOCKER_USERNAME}/onway-api:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped
  database:
    container_name: ${POSTGRES_HOST}
    image: postgres:15.13-alpine3.21
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgresdata:
